// Runtime secrets are provided via `wrangler secret put` and are NOT part of the binding
// types generated by `wrangler types` (which only sees vars and `.dev.vars`). Declare them
// here so type-checking succeeds everywhere, including CI where no `.dev.vars` exists.
interface Env {
  /** HMAC signing secret for session tokens. Set with `wrangler secret put TOKEN_SECRET`. */
  TOKEN_SECRET: string;
  /** Resend API key for sending login codes. Unset in dev → codes are shown on screen instead. */
  RESEND_API_KEY?: string;
  /** Verified Resend sender, e.g. "Pawbook <bookings@yourdomain.com>". Required to send email. */
  RESEND_FROM?: string;
  /**
   * Deployment environment. Only `'development'` (set in local `.dev.vars`) may show login codes
   * on screen when email is unconfigured; anything else (incl. unset) fails closed in production.
   */
  ENVIRONMENT?: string;
  /**
   * Comma-separated platform-owner emails (each trimmed + lowercased on parse). Owners log in
   * through the same form but route to the owner console. Unset/empty ⇒ no owners ⇒ owner
   * console unreachable (safe default). Set with `wrangler secret put OWNER_EMAILS`.
   */
  OWNER_EMAILS?: string;
  /** Google OAuth2 client id. `wrangler secret put GOOGLE_CLIENT_ID`. */
  GOOGLE_CLIENT_ID: string;
  /** Google OAuth2 client secret. `wrangler secret put GOOGLE_CLIENT_SECRET`. */
  GOOGLE_CLIENT_SECRET: string;
  /** Absolute URL of the global OAuth callback, registered in Google Cloud. Used in the consent
   *  URL and the code exchange (must match exactly). e.g. https://<worker>/oauth/google/callback */
  GOOGLE_OAUTH_REDIRECT_URI: string;
}
