// Runtime secrets are provided via `wrangler secret put` and are NOT part of the binding
// types generated by `wrangler types` (which only sees vars and `.dev.vars`). Declare them
// here so type-checking succeeds everywhere, including CI where no `.dev.vars` exists.
interface Env {
  /** HMAC signing secret for session tokens. Set with `wrangler secret put TOKEN_SECRET`. */
  TOKEN_SECRET: string;
  /** Resend API key for sending login codes. Unset in dev → codes are shown on screen instead. */
  RESEND_API_KEY?: string;
  /**
   * Verified Resend sender for account-access mail (login codes, password resets, signup
   * links) — customer, sitter, and owner alike. e.g. "Pawservation <no_reply@pawservation.com>".
   */
  RESEND_FROM_NOREPLY?: string;
  /**
   * Verified Resend sender for booking-related mail (invites, confirm/decline/cancel
   * notices). e.g. "Pawservation <booking@pawservation.com>".
   */
  RESEND_FROM_BOOKING?: string;
  /**
   * Deployment environment. Only `'development'` (set in local `.dev.vars`) may show login codes
   * on screen when email is unconfigured; anything else (incl. unset) fails closed in production —
   * except the two public /demo tenants, which always get the on-screen code regardless of
   * ENVIRONMENT or email configuration (see `DEMO_TENANT_SLUGS` in `server/routes/auth.ts`).
   */
  ENVIRONMENT?: string;
  /**
   * Comma-separated platform-owner emails (each trimmed + lowercased on parse). Owners log in
   * through the same form but route to the owner console. Unset/empty ⇒ no owners ⇒ owner
   * console unreachable (safe default). Set with `wrangler secret put OWNER_EMAILS`.
   */
  OWNER_EMAILS?: string;
  /**
   * Shared secret for `POST /api/:slug/admin/billing/events` (0017). Set with
   * `wrangler secret put BILLING_SHARED_SECRET`; never a var, never in `wrangler.jsonc`, never in a
   * log line. UNSET ⇒ the endpoint refuses everything, which is the correct behaviour for a
   * deployment that sells nothing.
   *
   * What it grants, exactly: setting one named tenant's `Plan` and `BilledUntil` — i.e. free
   * premium for that tenant. What it does not: it is not a session, it reads no booking, it mints no
   * credential, and it cannot touch `PremiumUntil` or `DisabledAt`.
   */
  BILLING_SHARED_SECRET?: string;
  /**
   * The value being rotated OUT, accepted alongside the one above so a rotation is an ORDERED PAIR
   * of deploys: set this to the old value here → the caller switches to the new one → delete this
   * (`wrangler secret delete BILLING_SHARED_SECRET_PREVIOUS`). Unset in steady state.
   *
   * TWO NAMED BINDINGS rather than one comma-separated value, unlike `OWNER_EMAILS`: that is a list
   * of identities whose length is genuinely open, this is a fixed pair with two roles — and a
   * comma-separated secret makes a secret containing a comma unrepresentable and turns a
   * trailing-space parse bug into a silent auth bypass.
   */
  BILLING_SHARED_SECRET_PREVIOUS?: string;
  /**
   * Absolute origin (scheme + host, no path) of the separately-deployed premium surface, published
   * on `GET /api/:slug/config` as `premium.origin`. REQUIRED by any deployment that HAS such a
   * surface; unset ⇒ `premium.origin` is `null` and none is advertised (`premiumOrigin`,
   * `server/lib/premium.ts`). There is deliberately NO default: this repo is the free product, and
   * a baked-in fallback would name a commercial deployment it does not contain while pointing every
   * other deployment's widgets at somebody else's host. Not a secret. It must be ABSOLUTE — the
   * widget and dashboard are also served from `*.workers.dev` hosts, which get no route matching,
   * so a relative path there resolves against the wrong host and the surface never loads; a value
   * that is not an absolute origin is refused exactly as unset is.
   */
  PREMIUM_ORIGIN?: string;
  /** Google OAuth2 client id. `wrangler secret put GOOGLE_CLIENT_ID`. */
  GOOGLE_CLIENT_ID: string;
  /**
   * Google OAuth2 client secret. `wrangler secret put GOOGLE_CLIENT_SECRET`.
   *
   * There is deliberately no GOOGLE_OAUTH_REDIRECT_URI beside these two: the callback URI is
   * derived per request from the origin the dashboard was opened on (`callbackUriFor`,
   * `server/lib/google-calendar.ts`), so the host-scoped CSRF cookie and the callback always share
   * a host. What replaces it is a Google Cloud Console entry per sitter-facing host.
   */
  GOOGLE_CLIENT_SECRET: string;
}
