-- Migration 0010. `Tenants.PremiumUntil` — the paid-through instant.
--
-- One nullable timestamp, and nothing else. NULL = free, which is what every tenant that exists
-- when this applies is: the column is added with NO DEFAULT, so SQLite stamps every existing row
-- NULL and applying the migration makes nobody a paying customer by accident. A non-NULL value is
-- read as "paid through this instant" and means nothing on its own — entitlement is
-- `PremiumUntil > now`, evaluated server-side at read time, never a stored boolean. A stored
-- boolean would need a job to flip it and would be wrong for as long as that job was late; a
-- timestamp compared on read cannot lapse late, because there is nothing to flip.
--
-- SHAPE, and why it matters that it is a string. SQLite has no date type, and this repo's existing
-- timestamps (`Tenants.CreatedAt`, `Tenants.DisabledAt`) are the `datetime('now')` form —
-- 'YYYY-MM-DD HH:MM:SS' in UTC. This column follows that exactly, and the owner route normalises
-- whatever the owner typed into it, because with a fixed-width UTC shape lexicographic order IS
-- chronological order: `PremiumUntil > now` is a plain string comparison that no timezone, offset
-- or 'T' separator can turn into a silently wrong answer. A mixed-format column would compare
-- '2027-01-01T00:00:00Z' against '2026-08-03 12:00:00' and put the future first — free access,
-- granted by a punctuation mark.
--
-- Deliberately NOT here: any notion of what premium BUYS. This repo has no feature to gate; it
-- records who has paid and publishes a derived boolean on the tenant's public config so a separate
-- surface can decide for itself. That surface's own entitlement check is its own business, and
-- keeping this column dumb is what stops the free product from growing an opinion about it.
--
-- CACHE KEY BUMPED IN THIS COMMIT (`tenant:<slug>:config:v2` -> `:v3`, server/lib/tenant-resolve.ts).
-- The request path READS this column off the KV-cached `Tenants` row, so entries written by the
-- previous worker would come back with `PremiumUntil` `undefined` for a whole 60-second TTL after
-- deploy — a sitter who has paid, reported as free, with the type insisting that cannot happen.
-- The new key means those entries are never read at all; they expire on their own.
--
-- Additive only (one bare `ALTER TABLE … ADD COLUMN`) and byte-identical in behaviour to the
-- pre-migration product for every existing row.
ALTER TABLE Tenants ADD COLUMN PremiumUntil TEXT;
